# Generated by Django 4.0.5 on 2022-06-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Team Leader', 'Team Leader'), ('Team Member', 'Team Member')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
